### ISSUE TITLE
сделать хедер

### ISSUE THREAD

**Issue by staszigzag** [kezlya/dev-team.club#15]
Create animation like on example website https://beshley.com/hendrix/theme_colors/default/index-particles.html

4 words in English and Russian

**Comment by kezlya** [comment]
- Dev Team Club
- Code
- Learn
- Enjoy

**Comment by kezlya** [comment]
![Screen Shot 2019-12-02 at 3 59 48 PM](https://user-images.githubusercontent.com/2000153/69961383-ca912980-151c-11ea-881b-abeb3aca53fc.png)

**Comment by kezlya** [comment]
Use this animation: 
https://css-tricks.com/snippets/css/typewriter-effect/
