### ISSUE TITLE
Projects section

### ISSUE THREAD

**Issue by KoblovaI** [kezlya/dev-team.club#6]
Our latest projects

**Comment by kezlya** [comment]
AntHive.IO

**Comment by kezlya** [comment]
[BreakKonnect.com](https://breakkonnect.com/)

**Comment by kezlya** [comment]
[CarsRespect.com](http://carsrespect.com/)

**Comment by kezlya** [comment]
![Screen Shot 2019-12-02 at 3 03 10 PM](https://user-images.githubusercontent.com/2000153/69958114-222b9700-1515-11ea-8cf9-ca477b3f0e0a.png)

**Comment by kezlya** [comment]
**AntHive.IO**
Coding challenge for beginners and seasoned developers. Tests your skills in various coding languages, challenge developers across the world. Realtime Ranking and leaderboard.

**Comment by kezlya** [comment]
**BreakKonnect.com**
World wide Dancers community with unique features to organize breakdancing battles. Advance payment features and Video Streaming of live events.

**Comment by kezlya** [comment]
**CarsRespect.com**
Website for cars dealership. Gives the owner flexible and easy way to manage promotions and vehicles for sale.

**Comment by KoblovaI** [comment]
CarsRespect.com
Сайт автосалона. Предоставляет возможность эффективно управлять системой скидок и акций для продажи и обслуживания транспортных средств.

**Comment by KoblovaI** [comment]
BreakKonnect.com
Всемирное сообщество танцоров с уникальной возможностью организации брейкданс-битв. А так же с сервисом авансовых платежей и потокового видео в прямом эфире.
