### ISSUE TITLE
Сделать секцию команде

### ISSUE THREAD

**Issue by KoblovaI** [kezlya/dev-team.club#7]

**Comment by kezlya** [comment]
https://www.nimbusthemes.com/preview/?theme=venture

**Comment by kezlya** [comment]
![Screen Shot 2019-11-28 at 11 33 50 PM](https://user-images.githubusercontent.com/2000153/69830822-9cb79680-1237-11ea-912a-472a45a8431b.png)

**Comment by kezlya** [comment]
Linkedin https://www.linkedin.com/in/vitaly-kezlya-450192b/
Youtube https://www.youtube.com/channel/UCtI9EdFlDo-4m98-m5SCbcw
